skip_docs

default_platform(:android)

platform :android do

  desc "Submit a new build to Internal Track on Play"
  lane :internal do
    upload_to_play_store(
      rollout: "0.5",
      track: "internal",
      aab:"../build/app/outputs/bundle/release/app-release.aab",
    )
  end

end
