skip_docs

default_platform(:android)

platform :android do

  lane :screenshots do
    capture_android_screenshots
    upload_to_play_store
  end

  lane :beta do
    # gradle(
    #   task: "clean"
    # )

    # gradle(
    #   task: 'assemble',
    #   build_type: 'Release'
    # )

    upload_to_play_store(
      rollout: "0.5",
      track: "beta",
      aab:"../build/app/outputs/bundle/release/app-release.aab",
    )
  end

  desc "Submit a new build to Internal Track on Play"
  lane :internal do
    upload_to_play_store(
      rollout: "0.5",
      track: "internal",
      aab:"../build/app/outputs/bundle/release/app-release.aab",
    )
  end

end
